version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: always
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start"]
  server:
    container_name: server
    build:
      context: .
    ports:
      - "5555:5000"
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "server"]